sudo: required
env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.3
 - GHCVER=8.0.1
 - GHCVER=head

script:
 - git clone https://github.com/jacereda/fsatrace.git
 - (cd fsatrace && make)
 - export PATH=$PATH:`pwd`/fsatrace
 - fsatrace v - -- echo fsatrace works
 - wget https://raw.github.com/ndmitchell/neil/master/travis.sh -O - --no-check-certificate --quiet | sh
